---
theme: jekyll-theme-cayman
title: 'Moment-of-truth'
page_title: 'this appears for og'
headline: 'testing headline'
description: 'testing description'
logo: '/assets/imgs/favicon.ico'
defaults:
  - scope:
      path: ''
    values:
      image: 'assets/imgs/og-dp.jpg'
---

# For reference, Jekyll SEO Tag:
# https://github.com/jekyll/jekyll-seo-tag/blob/master/lib/template.html
