---
theme: jekyll-theme-cayman
title: 'Moment-of-truth'
headline: 'testing headline'
description: 'testing description'
logo: '/assets/imgs/favicon.ico'
image:
  path: '/assets/imgs/new-og-dp-resized.png'
  alt: Page Cover
---
