name: Add Updated to README

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

env:
  REPO_OWNER: ${{ github.repository_owner }}
  REPO_NAME: ${{ github.repository }}

jobs:
  update-by-pr:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checking out the repo
        uses: actions/checkout@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          
      - name: Setup Python
        uses: actions/setup-python@v4.7.1
          
      - name: Getting PR details
        run: |
          touch pr.json
          gh pr view 19 --json author,url,files > pr.json 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Updating log file
        run: |
          python update_contributors_log.py
          cat .github/data/contributors-log.json
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          
      - name: Updating index.md file
        run: |
          python update_index_md.py
          cat .github/data/contributors-log.json

      - name: Commit and Push
        run: |
          if [ "$(git status | grep 'Changes not staged\|Untracked files')" ]; then
            git diff
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git commit -am "Updated Contributors Details"
            git push origin main
          fi
